
// -*- C++ -*-
// $Id: Version.h 86014 2009-07-13 17:32:55Z mesnier_p $
// This is file was automatically generated by \$ACE_ROOT/bin/make_release.

#define ACE_MAJOR_VERSION 5
#define ACE_MINOR_VERSION 7
#define ACE_BETA_VERSION 1
#define ACE_VERSION "5.7.1"
